/* ============================================================
   ELYSIAN FINDS — Built-in fallback catalogue
   ------------------------------------------------------------
   This list is only a SAFETY NET. Once a Google Sheet is
   connected (see js/data-source.js and ADMIN-GUIDE.md), the
   live sheet is the real source of truth and whoever manages
   the catalogue never needs to touch this file again.
   ============================================================ */

const MEESHO_STORE_URL = "https://www.meesho.com/"; // TODO: replace with your storefront URL
const WHATSAPP_NUMBER = "917620043844"; // TODO: replace with your WhatsApp business number

const PRODUCTS_FALLBACK = [
  {
    id: "p01",
    name: "Amara Solitaire Ring",
    category: "Rings",
    occasion: "Everyday",
    price: 1499,
    tag: "Bestseller",
    icon: "ring_round",
    gallery: ["ring_round", "ring_oval"],
    material: "Gold-plated brass",
    stone: "Cubic zirconia",
    weight: "3.2 g",
    plating: "18k gold micron plating",
    description: "A clean round-cut solitaire set on a slender polished band. Understated enough for daily wear, bright enough to catch the light every time you move your hand.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p02",
    name: "Vesper Twist Band",
    category: "Rings",
    occasion: "Everyday",
    price: 999,
    tag: "New",
    icon: "ring_oval",
    gallery: ["ring_oval", "ring_round"],
    material: "Gold-plated brass",
    stone: "None",
    weight: "2.6 g",
    plating: "18k gold micron plating",
    description: "A double-band twist that stacks beautifully with the Amara or wears alone. Smooth interior edge so it never snags on knits or scarves.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p03",
    name: "Rani Kundan Ring",
    category: "Rings",
    occasion: "Festive",
    price: 1899,
    tag: "",
    icon: "ring_round",
    gallery: ["ring_round"],
    material: "Kundan on brass base",
    stone: "Kundan, faux pearl",
    weight: "4.1 g",
    plating: "Antique gold finish",
    description: "Traditional kundan work set in an antique gold finish, finished with a single hanging pearl. Pulls together a festive look without competing with a heavier necklace.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p04",
    name: "Meera Layered Necklace",
    category: "Necklaces",
    occasion: "Party",
    price: 2299,
    tag: "Bestseller",
    icon: "necklace_layered",
    gallery: ["necklace_layered", "necklace_pendant"],
    material: "Gold-plated brass chain",
    stone: "None",
    weight: "18 g",
    plating: "18k gold micron plating",
    description: "Two chains of different lengths, worn as one. Sits well over both a plain kurta and a plunge neckline, which is why it's the piece we restock most often.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p05",
    name: "Anaya Pendant Chain",
    category: "Necklaces",
    occasion: "Everyday",
    price: 1299,
    tag: "",
    icon: "necklace_pendant",
    gallery: ["necklace_pendant"],
    material: "Gold-plated brass",
    stone: "Cubic zirconia",
    weight: "9 g",
    plating: "18k gold micron plating",
    description: "A single teardrop pendant on a fine chain. Light enough to forget you're wearing it, which is exactly the point of an everyday piece.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p06",
    name: "Suhana Bridal Choker Set",
    category: "Necklaces",
    occasion: "Bridal",
    price: 4499,
    tag: "Bridal",
    icon: "pendant_set",
    gallery: ["pendant_set", "necklace_layered"],
    material: "Kundan-polki on brass base",
    stone: "Kundan, polki, faux emerald",
    weight: "62 g",
    plating: "Antique gold finish",
    description: "A full choker and drop set built for the main event — reception-ready with matching earrings included. Comes with a maang tikka in the same finish.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p07",
    name: "Ira Drop Earrings",
    category: "Earrings",
    occasion: "Party",
    price: 899,
    tag: "New",
    icon: "earring_drop",
    gallery: ["earring_drop", "earring_stud"],
    material: "Gold-plated brass",
    stone: "Cubic zirconia",
    weight: "5.4 g / pair",
    plating: "18k gold micron plating",
    description: "A teardrop that moves with you, not stiff or heavy at the earlobe. Our most-photographed earring for evening looks.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p08",
    name: "Kiara Stud Pair",
    category: "Earrings",
    occasion: "Everyday",
    price: 599,
    tag: "Bestseller",
    icon: "earring_stud",
    gallery: ["earring_stud"],
    material: "Gold-plated brass",
    stone: "None",
    weight: "2.8 g / pair",
    plating: "18k gold micron plating",
    description: "A rounded stud with a brushed matte finish. Sits close to the ear, so it works under a dupatta or a hood alike.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p09",
    name: "Zoya Jhumka",
    category: "Earrings",
    occasion: "Festive",
    price: 1199,
    tag: "",
    icon: "earring_drop",
    gallery: ["earring_drop"],
    material: "Kundan on brass base",
    stone: "Kundan, faux pearl",
    weight: "12 g / pair",
    plating: "Antique gold finish",
    description: "A classic bell-shaped jhumka with a pearl fringe. Pairs naturally with the Rani Kundan Ring for a coordinated festive set.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p10",
    name: "Devika Single Bangle",
    category: "Bangles",
    occasion: "Everyday",
    price: 799,
    tag: "",
    icon: "bangle_single",
    gallery: ["bangle_single"],
    material: "Gold-plated brass",
    stone: "None",
    weight: "22 g",
    plating: "18k gold micron plating",
    description: "A wide, solid bangle with a subtle etched border. Holds its shine well with the occasional soft-cloth wipe.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p11",
    name: "Naina Stacking Set (3pc)",
    category: "Bangles",
    occasion: "Festive",
    price: 1699,
    tag: "New",
    icon: "bangle_stack",
    gallery: ["bangle_stack", "bangle_single"],
    material: "Gold-plated brass",
    stone: "None",
    weight: "58 g / set",
    plating: "Mixed antique & polished finish",
    description: "Three bangles in complementary finishes, sized to sit together without clashing. Sold as a set of three.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p12",
    name: "Tara Mangalsutra",
    category: "Mangalsutra",
    occasion: "Everyday",
    price: 1999,
    tag: "Bestseller",
    icon: "mangalsutra",
    gallery: ["mangalsutra"],
    material: "Black beads with gold-plated brass",
    stone: "Cubic zirconia",
    weight: "14 g",
    plating: "18k gold micron plating",
    description: "A shorter, everyday-length mangalsutra with a compact pendant. Comfortable under office wear and doesn't tangle with other chains.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p13",
    name: "Leela Vintage Brooch",
    category: "Accessories",
    occasion: "Party",
    price: 699,
    tag: "",
    icon: "brooch",
    gallery: ["brooch"],
    material: "Gold-plated brass",
    stone: "Cubic zirconia",
    weight: "8 g",
    plating: "18k gold micron plating",
    description: "A compact filigree brooch that dresses up a plain saree pin or blazer lapel. Secure pin-back, no magnet to lose.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p14",
    name: "Payal Anklet Pair",
    category: "Accessories",
    occasion: "Everyday",
    price: 749,
    tag: "",
    icon: "anklet",
    gallery: ["anklet"],
    material: "Gold-plated brass",
    stone: "None",
    weight: "16 g / pair",
    plating: "18k gold micron plating",
    description: "A classic ghungroo-free anklet with a light chime from the small charms. Adjustable clasp fits most ankle sizes.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p15",
    name: "Ishaani Bridal Earrings",
    category: "Earrings",
    occasion: "Bridal",
    price: 2199,
    tag: "Bridal",
    icon: "earring_drop",
    gallery: ["earring_drop", "earring_stud"],
    material: "Kundan-polki on brass base",
    stone: "Kundan, polki, faux emerald",
    weight: "16 g / pair",
    plating: "Antique gold finish",
    description: "The matching earring pair for the Suhana Choker Set, also sold separately for those styling their own bridal look.",
    meeshoUrl: MEESHO_STORE_URL,
  },
  {
    id: "p16",
    name: "Firoza Pendant Set",
    category: "Necklaces",
    occasion: "Festive",
    price: 1599,
    tag: "",
    icon: "pendant_set",
    gallery: ["pendant_set", "necklace_pendant"],
    material: "Gold-plated brass",
    stone: "Faux turquoise",
    weight: "20 g",
    plating: "18k gold micron plating",
    description: "A turquoise-tone pendant set with matching drop earrings — a warm-weather festive pairing that photographs well against most fabric colors.",
    meeshoUrl: MEESHO_STORE_URL,
  },
];

/* CATEGORIES is now computed dynamically by computeCategories() in data-source.js,
   since the active product list may come from a live Google Sheet rather than
   this fallback array. */